Test: Add additional debugging to gerrit-merge.yaml
Change-Id: Icd5c9020a25b9a625d09d0845c4b2f2c526daffe
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/gerrit-merge.yaml b/.github/workflows/gerrit-merge.yaml
--- a/.github/workflows/gerrit-merge.yaml
+++ b/.github/workflows/gerrit-merge.yaml
@@ -86,19 +86,66 @@ jobs:
     outputs:
       nexus_password: ${{ steps.load_secrets.outputs.NEXUS_PASSWORD }}
     steps:
+      # yamllint disable-line rule:line-length
+      - uses: lfit/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63 # v0.9
+        with:
+          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
+          gerrit-url: ${{ vars.GERRIT_URL }}
+          delay: "10s"  # Allow time for GitHub mirroring
+
+      - name: "Extract Gerrit project from .gitreview"
+        shell: bash
+        run: |
+          # Extract Gerrit project from .gitreview
+          GERRIT_PROJECT=$(grep 'project=' .gitreview | awk -F= '{print $2}')
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ] || [ -z "$GERRIT_PROJECT" ]; then
+            echo "Error: Unable to extract Gerrit project from .gitreview"
+            exit 1
+          else
+            echo "GERRIT_PROJECT=$GERRIT_PROJECT" >> $GITHUB_ENV
+            echo "GERRIT_PROJECT=$GERRIT_PROJECT" >> $GITHUB_OUTPUT
+            echo "Extracted Gerrit project name: $GERRIT_PROJECT" >> $GITHUB_STEP_SUMMARY
+          fi
+
       - name: Load secrets from 1Password
         id: load_secrets
         # yamllint disable-line rule:line-length
         uses: 1password/load-secrets-action@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3.0.0
         env:
           OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
-          NEXUS_PASSWORD: op://6n4qm2onchsinyyeuxmcfbo7ne/oam-oam-controller/password
+          NEXUS_PASSWORD: op://6n4qm2onchsinyyeuxmcfbo7ne/${{ env.GERRIT_PROJECT }}/password
+
+      - name: "Show SHA1SUM of 1Password credential"
+        shell: bash
+        run: |
+          # Show SHA1SUM of 1Password credential
+          SHA1SUM_CMD=$(which sha1sum)
+          if [ ! -x "$SHA1SUM_CMD" ]; then
+            echo "Error: sha1sum binary not found in PATH ❌"; exit 1
+          fi
+          SHA1SUM=$(echo -n ${{ env.GERRIT_PROJECT }} | "$SHA1SUM_CMD")
+          echo "Credential sha1sum: $SHA1SUM" >> $GITHUB_OUTPUT
+          echo "Credential sha1sum: $SHA1SUM" >> $GITHUB_STEP_SUMMARY
+
+  check-secrets:
+    needs: [notify, sanitize, load-secrets]
+    runs-on: ubuntu-latest
+    env:
+      NEXUS_PASSWORD: ${{ needs.load-secrets.outputs.nexus_password }}
+    steps:
+      - name: "Check extracted secret availability from second job"
+        shell: bash
+        run: |
+          # Show SHA1SUM of 1Password credential
+          echo "Credential sha1sum: $NEXUS_PASSWORD" >> $GITHUB_OUTPUT
+          echo "Credential sha1sum: $NEXUS_PASSWORD" >> $GITHUB_STEP_SUMMARY
 
   maven-merge:
     needs: [notify, sanitize, load-secrets]
     # yamllint disable-line rule:line-length
     uses: lfit/releng-reusable-workflows/.github/workflows/compose-make-merge.yaml@f318aaac9f4fce73a8059fe95ba9080833e018c2
-    secrets:                                                 # forward secrets
+    secrets:
       NEXUS_PASSWORD: ${{ needs.load-secrets.outputs.nexus_password }}
     with:
       GERRIT_BRANCH: ${{ inputs.GERRIT_BRANCH }}
